// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: balance_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_balance_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_balance_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_balance_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetBalanceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiResponse   *APIResponse           `protobuf:"bytes,1,opt,name=api_response,json=apiResponse,proto3" json:"api_response,omitempty"`
	Balance       *Balance               `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_balance_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_balance_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_balance_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetBalanceResponse) GetApiResponse() *APIResponse {
	if x != nil {
		return x.ApiResponse
	}
	return nil
}

func (x *GetBalanceResponse) GetBalance() *Balance {
	if x != nil {
		return x.Balance
	}
	return nil
}

type Balance struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AvailableBalance float64                `protobuf:"fixed64,2,opt,name=available_balance,json=availableBalance,proto3" json:"available_balance,omitempty"`
	TotalBalance     float64                `protobuf:"fixed64,3,opt,name=total_balance,json=totalBalance,proto3" json:"total_balance,omitempty"`
	ReservedBalance  float64                `protobuf:"fixed64,4,opt,name=reserved_balance,json=reservedBalance,proto3" json:"reserved_balance,omitempty"`
	Currency         string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	LastUpdated      string                 `protobuf:"bytes,6,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Balance) Reset() {
	*x = Balance{}
	mi := &file_balance_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Balance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Balance) ProtoMessage() {}

func (x *Balance) ProtoReflect() protoreflect.Message {
	mi := &file_balance_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Balance.ProtoReflect.Descriptor instead.
func (*Balance) Descriptor() ([]byte, []int) {
	return file_balance_service_proto_rawDescGZIP(), []int{2}
}

func (x *Balance) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Balance) GetAvailableBalance() float64 {
	if x != nil {
		return x.AvailableBalance
	}
	return 0
}

func (x *Balance) GetTotalBalance() float64 {
	if x != nil {
		return x.TotalBalance
	}
	return 0
}

func (x *Balance) GetReservedBalance() float64 {
	if x != nil {
		return x.ReservedBalance
	}
	return 0
}

func (x *Balance) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Balance) GetLastUpdated() string {
	if x != nil {
		return x.LastUpdated
	}
	return ""
}

var File_balance_service_proto protoreflect.FileDescriptor

const file_balance_service_proto_rawDesc = "" +
	"\n" +
	"\x15balance_service.proto\x12\x0fhub_investments\x1a\fcommon.proto\",\n" +
	"\x11GetBalanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x89\x01\n" +
	"\x12GetBalanceResponse\x12?\n" +
	"\fapi_response\x18\x01 \x01(\v2\x1c.hub_investments.APIResponseR\vapiResponse\x122\n" +
	"\abalance\x18\x02 \x01(\v2\x18.hub_investments.BalanceR\abalance\"\xde\x01\n" +
	"\aBalance\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12+\n" +
	"\x11available_balance\x18\x02 \x01(\x01R\x10availableBalance\x12#\n" +
	"\rtotal_balance\x18\x03 \x01(\x01R\ftotalBalance\x12)\n" +
	"\x10reserved_balance\x18\x04 \x01(\x01R\x0freservedBalance\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12!\n" +
	"\flast_updated\x18\x06 \x01(\tR\vlastUpdated2g\n" +
	"\x0eBalanceService\x12U\n" +
	"\n" +
	"GetBalance\x12\".hub_investments.GetBalanceRequest\x1a#.hub_investments.GetBalanceResponseB\tZ\a./protob\x06proto3"

var (
	file_balance_service_proto_rawDescOnce sync.Once
	file_balance_service_proto_rawDescData []byte
)

func file_balance_service_proto_rawDescGZIP() []byte {
	file_balance_service_proto_rawDescOnce.Do(func() {
		file_balance_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_balance_service_proto_rawDesc), len(file_balance_service_proto_rawDesc)))
	})
	return file_balance_service_proto_rawDescData
}

var file_balance_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_balance_service_proto_goTypes = []any{
	(*GetBalanceRequest)(nil),  // 0: hub_investments.GetBalanceRequest
	(*GetBalanceResponse)(nil), // 1: hub_investments.GetBalanceResponse
	(*Balance)(nil),            // 2: hub_investments.Balance
	(*APIResponse)(nil),        // 3: hub_investments.APIResponse
}
var file_balance_service_proto_depIdxs = []int32{
	3, // 0: hub_investments.GetBalanceResponse.api_response:type_name -> hub_investments.APIResponse
	2, // 1: hub_investments.GetBalanceResponse.balance:type_name -> hub_investments.Balance
	0, // 2: hub_investments.BalanceService.GetBalance:input_type -> hub_investments.GetBalanceRequest
	1, // 3: hub_investments.BalanceService.GetBalance:output_type -> hub_investments.GetBalanceResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_balance_service_proto_init() }
func file_balance_service_proto_init() {
	if File_balance_service_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_balance_service_proto_rawDesc), len(file_balance_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_balance_service_proto_goTypes,
		DependencyIndexes: file_balance_service_proto_depIdxs,
		MessageInfos:      file_balance_service_proto_msgTypes,
	}.Build()
	File_balance_service_proto = out.File
	file_balance_service_proto_goTypes = nil
	file_balance_service_proto_depIdxs = nil
}
