// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: market_data_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMarketDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMarketDataRequest) Reset() {
	*x = GetMarketDataRequest{}
	mi := &file_market_data_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMarketDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMarketDataRequest) ProtoMessage() {}

func (x *GetMarketDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMarketDataRequest.ProtoReflect.Descriptor instead.
func (*GetMarketDataRequest) Descriptor() ([]byte, []int) {
	return file_market_data_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetMarketDataRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type GetMarketDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiResponse   *APIResponse           `protobuf:"bytes,1,opt,name=api_response,json=apiResponse,proto3" json:"api_response,omitempty"`
	MarketData    *MarketData            `protobuf:"bytes,2,opt,name=market_data,json=marketData,proto3" json:"market_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMarketDataResponse) Reset() {
	*x = GetMarketDataResponse{}
	mi := &file_market_data_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMarketDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMarketDataResponse) ProtoMessage() {}

func (x *GetMarketDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMarketDataResponse.ProtoReflect.Descriptor instead.
func (*GetMarketDataResponse) Descriptor() ([]byte, []int) {
	return file_market_data_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetMarketDataResponse) GetApiResponse() *APIResponse {
	if x != nil {
		return x.ApiResponse
	}
	return nil
}

func (x *GetMarketDataResponse) GetMarketData() *MarketData {
	if x != nil {
		return x.MarketData
	}
	return nil
}

type GetAssetDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssetDetailsRequest) Reset() {
	*x = GetAssetDetailsRequest{}
	mi := &file_market_data_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssetDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetDetailsRequest) ProtoMessage() {}

func (x *GetAssetDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetAssetDetailsRequest) Descriptor() ([]byte, []int) {
	return file_market_data_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetAssetDetailsRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type GetAssetDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiResponse   *APIResponse           `protobuf:"bytes,1,opt,name=api_response,json=apiResponse,proto3" json:"api_response,omitempty"`
	Asset         *AssetDetails          `protobuf:"bytes,2,opt,name=asset,proto3" json:"asset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssetDetailsResponse) Reset() {
	*x = GetAssetDetailsResponse{}
	mi := &file_market_data_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssetDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetDetailsResponse) ProtoMessage() {}

func (x *GetAssetDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetAssetDetailsResponse) Descriptor() ([]byte, []int) {
	return file_market_data_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetAssetDetailsResponse) GetApiResponse() *APIResponse {
	if x != nil {
		return x.ApiResponse
	}
	return nil
}

func (x *GetAssetDetailsResponse) GetAsset() *AssetDetails {
	if x != nil {
		return x.Asset
	}
	return nil
}

type GetBatchMarketDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbols       []string               `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBatchMarketDataRequest) Reset() {
	*x = GetBatchMarketDataRequest{}
	mi := &file_market_data_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBatchMarketDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBatchMarketDataRequest) ProtoMessage() {}

func (x *GetBatchMarketDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBatchMarketDataRequest.ProtoReflect.Descriptor instead.
func (*GetBatchMarketDataRequest) Descriptor() ([]byte, []int) {
	return file_market_data_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetBatchMarketDataRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

type GetBatchMarketDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiResponse   *APIResponse           `protobuf:"bytes,1,opt,name=api_response,json=apiResponse,proto3" json:"api_response,omitempty"`
	MarketData    []*MarketData          `protobuf:"bytes,2,rep,name=market_data,json=marketData,proto3" json:"market_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBatchMarketDataResponse) Reset() {
	*x = GetBatchMarketDataResponse{}
	mi := &file_market_data_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBatchMarketDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBatchMarketDataResponse) ProtoMessage() {}

func (x *GetBatchMarketDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBatchMarketDataResponse.ProtoReflect.Descriptor instead.
func (*GetBatchMarketDataResponse) Descriptor() ([]byte, []int) {
	return file_market_data_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetBatchMarketDataResponse) GetApiResponse() *APIResponse {
	if x != nil {
		return x.ApiResponse
	}
	return nil
}

func (x *GetBatchMarketDataResponse) GetMarketData() []*MarketData {
	if x != nil {
		return x.MarketData
	}
	return nil
}

type MarketData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	CompanyName   string                 `protobuf:"bytes,2,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	CurrentPrice  float64                `protobuf:"fixed64,3,opt,name=current_price,json=currentPrice,proto3" json:"current_price,omitempty"`
	PreviousClose float64                `protobuf:"fixed64,4,opt,name=previous_close,json=previousClose,proto3" json:"previous_close,omitempty"`
	OpenPrice     float64                `protobuf:"fixed64,5,opt,name=open_price,json=openPrice,proto3" json:"open_price,omitempty"`
	HighPrice     float64                `protobuf:"fixed64,6,opt,name=high_price,json=highPrice,proto3" json:"high_price,omitempty"`
	LowPrice      float64                `protobuf:"fixed64,7,opt,name=low_price,json=lowPrice,proto3" json:"low_price,omitempty"`
	Change        float64                `protobuf:"fixed64,8,opt,name=change,proto3" json:"change,omitempty"`
	ChangePercent float64                `protobuf:"fixed64,9,opt,name=change_percent,json=changePercent,proto3" json:"change_percent,omitempty"`
	Volume        int64                  `protobuf:"varint,10,opt,name=volume,proto3" json:"volume,omitempty"`
	LastUpdated   string                 `protobuf:"bytes,11,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketData) Reset() {
	*x = MarketData{}
	mi := &file_market_data_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketData) ProtoMessage() {}

func (x *MarketData) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketData.ProtoReflect.Descriptor instead.
func (*MarketData) Descriptor() ([]byte, []int) {
	return file_market_data_service_proto_rawDescGZIP(), []int{6}
}

func (x *MarketData) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *MarketData) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *MarketData) GetCurrentPrice() float64 {
	if x != nil {
		return x.CurrentPrice
	}
	return 0
}

func (x *MarketData) GetPreviousClose() float64 {
	if x != nil {
		return x.PreviousClose
	}
	return 0
}

func (x *MarketData) GetOpenPrice() float64 {
	if x != nil {
		return x.OpenPrice
	}
	return 0
}

func (x *MarketData) GetHighPrice() float64 {
	if x != nil {
		return x.HighPrice
	}
	return 0
}

func (x *MarketData) GetLowPrice() float64 {
	if x != nil {
		return x.LowPrice
	}
	return 0
}

func (x *MarketData) GetChange() float64 {
	if x != nil {
		return x.Change
	}
	return 0
}

func (x *MarketData) GetChangePercent() float64 {
	if x != nil {
		return x.ChangePercent
	}
	return 0
}

func (x *MarketData) GetVolume() int64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *MarketData) GetLastUpdated() string {
	if x != nil {
		return x.LastUpdated
	}
	return ""
}

type AssetDetails struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Symbol           string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	CompanyName      string                 `protobuf:"bytes,2,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	Sector           string                 `protobuf:"bytes,3,opt,name=sector,proto3" json:"sector,omitempty"`
	Industry         string                 `protobuf:"bytes,4,opt,name=industry,proto3" json:"industry,omitempty"`
	Description      string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	MarketCap        float64                `protobuf:"fixed64,6,opt,name=market_cap,json=marketCap,proto3" json:"market_cap,omitempty"`
	PeRatio          float64                `protobuf:"fixed64,7,opt,name=pe_ratio,json=peRatio,proto3" json:"pe_ratio,omitempty"`
	DividendYield    float64                `protobuf:"fixed64,8,opt,name=dividend_yield,json=dividendYield,proto3" json:"dividend_yield,omitempty"`
	FiftyTwoWeekHigh float64                `protobuf:"fixed64,9,opt,name=fifty_two_week_high,json=fiftyTwoWeekHigh,proto3" json:"fifty_two_week_high,omitempty"`
	FiftyTwoWeekLow  float64                `protobuf:"fixed64,10,opt,name=fifty_two_week_low,json=fiftyTwoWeekLow,proto3" json:"fifty_two_week_low,omitempty"`
	Currency         string                 `protobuf:"bytes,11,opt,name=currency,proto3" json:"currency,omitempty"`
	Exchange         string                 `protobuf:"bytes,12,opt,name=exchange,proto3" json:"exchange,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AssetDetails) Reset() {
	*x = AssetDetails{}
	mi := &file_market_data_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetDetails) ProtoMessage() {}

func (x *AssetDetails) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetDetails.ProtoReflect.Descriptor instead.
func (*AssetDetails) Descriptor() ([]byte, []int) {
	return file_market_data_service_proto_rawDescGZIP(), []int{7}
}

func (x *AssetDetails) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *AssetDetails) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *AssetDetails) GetSector() string {
	if x != nil {
		return x.Sector
	}
	return ""
}

func (x *AssetDetails) GetIndustry() string {
	if x != nil {
		return x.Industry
	}
	return ""
}

func (x *AssetDetails) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AssetDetails) GetMarketCap() float64 {
	if x != nil {
		return x.MarketCap
	}
	return 0
}

func (x *AssetDetails) GetPeRatio() float64 {
	if x != nil {
		return x.PeRatio
	}
	return 0
}

func (x *AssetDetails) GetDividendYield() float64 {
	if x != nil {
		return x.DividendYield
	}
	return 0
}

func (x *AssetDetails) GetFiftyTwoWeekHigh() float64 {
	if x != nil {
		return x.FiftyTwoWeekHigh
	}
	return 0
}

func (x *AssetDetails) GetFiftyTwoWeekLow() float64 {
	if x != nil {
		return x.FiftyTwoWeekLow
	}
	return 0
}

func (x *AssetDetails) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *AssetDetails) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

var File_market_data_service_proto protoreflect.FileDescriptor

const file_market_data_service_proto_rawDesc = "" +
	"\n" +
	"\x19market_data_service.proto\x12\x0fhub_investments\x1a\fcommon.proto\".\n" +
	"\x14GetMarketDataRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\"\x96\x01\n" +
	"\x15GetMarketDataResponse\x12?\n" +
	"\fapi_response\x18\x01 \x01(\v2\x1c.hub_investments.APIResponseR\vapiResponse\x12<\n" +
	"\vmarket_data\x18\x02 \x01(\v2\x1b.hub_investments.MarketDataR\n" +
	"marketData\"0\n" +
	"\x16GetAssetDetailsRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\"\x8f\x01\n" +
	"\x17GetAssetDetailsResponse\x12?\n" +
	"\fapi_response\x18\x01 \x01(\v2\x1c.hub_investments.APIResponseR\vapiResponse\x123\n" +
	"\x05asset\x18\x02 \x01(\v2\x1d.hub_investments.AssetDetailsR\x05asset\"5\n" +
	"\x19GetBatchMarketDataRequest\x12\x18\n" +
	"\asymbols\x18\x01 \x03(\tR\asymbols\"\x9b\x01\n" +
	"\x1aGetBatchMarketDataResponse\x12?\n" +
	"\fapi_response\x18\x01 \x01(\v2\x1c.hub_investments.APIResponseR\vapiResponse\x12<\n" +
	"\vmarket_data\x18\x02 \x03(\v2\x1b.hub_investments.MarketDataR\n" +
	"marketData\"\xe8\x02\n" +
	"\n" +
	"MarketData\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12!\n" +
	"\fcompany_name\x18\x02 \x01(\tR\vcompanyName\x12#\n" +
	"\rcurrent_price\x18\x03 \x01(\x01R\fcurrentPrice\x12%\n" +
	"\x0eprevious_close\x18\x04 \x01(\x01R\rpreviousClose\x12\x1d\n" +
	"\n" +
	"open_price\x18\x05 \x01(\x01R\topenPrice\x12\x1d\n" +
	"\n" +
	"high_price\x18\x06 \x01(\x01R\thighPrice\x12\x1b\n" +
	"\tlow_price\x18\a \x01(\x01R\blowPrice\x12\x16\n" +
	"\x06change\x18\b \x01(\x01R\x06change\x12%\n" +
	"\x0echange_percent\x18\t \x01(\x01R\rchangePercent\x12\x16\n" +
	"\x06volume\x18\n" +
	" \x01(\x03R\x06volume\x12!\n" +
	"\flast_updated\x18\v \x01(\tR\vlastUpdated\"\x94\x03\n" +
	"\fAssetDetails\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12!\n" +
	"\fcompany_name\x18\x02 \x01(\tR\vcompanyName\x12\x16\n" +
	"\x06sector\x18\x03 \x01(\tR\x06sector\x12\x1a\n" +
	"\bindustry\x18\x04 \x01(\tR\bindustry\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"market_cap\x18\x06 \x01(\x01R\tmarketCap\x12\x19\n" +
	"\bpe_ratio\x18\a \x01(\x01R\apeRatio\x12%\n" +
	"\x0edividend_yield\x18\b \x01(\x01R\rdividendYield\x12-\n" +
	"\x13fifty_two_week_high\x18\t \x01(\x01R\x10fiftyTwoWeekHigh\x12+\n" +
	"\x12fifty_two_week_low\x18\n" +
	" \x01(\x01R\x0ffiftyTwoWeekLow\x12\x1a\n" +
	"\bcurrency\x18\v \x01(\tR\bcurrency\x12\x1a\n" +
	"\bexchange\x18\f \x01(\tR\bexchange2\xc8\x02\n" +
	"\x11MarketDataService\x12^\n" +
	"\rGetMarketData\x12%.hub_investments.GetMarketDataRequest\x1a&.hub_investments.GetMarketDataResponse\x12d\n" +
	"\x0fGetAssetDetails\x12'.hub_investments.GetAssetDetailsRequest\x1a(.hub_investments.GetAssetDetailsResponse\x12m\n" +
	"\x12GetBatchMarketData\x12*.hub_investments.GetBatchMarketDataRequest\x1a+.hub_investments.GetBatchMarketDataResponseB\tZ\a./protob\x06proto3"

var (
	file_market_data_service_proto_rawDescOnce sync.Once
	file_market_data_service_proto_rawDescData []byte
)

func file_market_data_service_proto_rawDescGZIP() []byte {
	file_market_data_service_proto_rawDescOnce.Do(func() {
		file_market_data_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_market_data_service_proto_rawDesc), len(file_market_data_service_proto_rawDesc)))
	})
	return file_market_data_service_proto_rawDescData
}

var file_market_data_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_market_data_service_proto_goTypes = []any{
	(*GetMarketDataRequest)(nil),       // 0: hub_investments.GetMarketDataRequest
	(*GetMarketDataResponse)(nil),      // 1: hub_investments.GetMarketDataResponse
	(*GetAssetDetailsRequest)(nil),     // 2: hub_investments.GetAssetDetailsRequest
	(*GetAssetDetailsResponse)(nil),    // 3: hub_investments.GetAssetDetailsResponse
	(*GetBatchMarketDataRequest)(nil),  // 4: hub_investments.GetBatchMarketDataRequest
	(*GetBatchMarketDataResponse)(nil), // 5: hub_investments.GetBatchMarketDataResponse
	(*MarketData)(nil),                 // 6: hub_investments.MarketData
	(*AssetDetails)(nil),               // 7: hub_investments.AssetDetails
	(*APIResponse)(nil),                // 8: hub_investments.APIResponse
}
var file_market_data_service_proto_depIdxs = []int32{
	8, // 0: hub_investments.GetMarketDataResponse.api_response:type_name -> hub_investments.APIResponse
	6, // 1: hub_investments.GetMarketDataResponse.market_data:type_name -> hub_investments.MarketData
	8, // 2: hub_investments.GetAssetDetailsResponse.api_response:type_name -> hub_investments.APIResponse
	7, // 3: hub_investments.GetAssetDetailsResponse.asset:type_name -> hub_investments.AssetDetails
	8, // 4: hub_investments.GetBatchMarketDataResponse.api_response:type_name -> hub_investments.APIResponse
	6, // 5: hub_investments.GetBatchMarketDataResponse.market_data:type_name -> hub_investments.MarketData
	0, // 6: hub_investments.MarketDataService.GetMarketData:input_type -> hub_investments.GetMarketDataRequest
	2, // 7: hub_investments.MarketDataService.GetAssetDetails:input_type -> hub_investments.GetAssetDetailsRequest
	4, // 8: hub_investments.MarketDataService.GetBatchMarketData:input_type -> hub_investments.GetBatchMarketDataRequest
	1, // 9: hub_investments.MarketDataService.GetMarketData:output_type -> hub_investments.GetMarketDataResponse
	3, // 10: hub_investments.MarketDataService.GetAssetDetails:output_type -> hub_investments.GetAssetDetailsResponse
	5, // 11: hub_investments.MarketDataService.GetBatchMarketData:output_type -> hub_investments.GetBatchMarketDataResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_market_data_service_proto_init() }
func file_market_data_service_proto_init() {
	if File_market_data_service_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_market_data_service_proto_rawDesc), len(file_market_data_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_market_data_service_proto_goTypes,
		DependencyIndexes: file_market_data_service_proto_depIdxs,
		MessageInfos:      file_market_data_service_proto_msgTypes,
	}.Build()
	File_market_data_service_proto = out.File
	file_market_data_service_proto_goTypes = nil
	file_market_data_service_proto_depIdxs = nil
}
