// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: market_data_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MarketDataService_GetMarketData_FullMethodName      = "/hub_investments.MarketDataService/GetMarketData"
	MarketDataService_GetAssetDetails_FullMethodName    = "/hub_investments.MarketDataService/GetAssetDetails"
	MarketDataService_GetBatchMarketData_FullMethodName = "/hub_investments.MarketDataService/GetBatchMarketData"
)

// MarketDataServiceClient is the client API for MarketDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MarketDataService provides market data operations
type MarketDataServiceClient interface {
	// GetMarketData retrieves market data for a specific symbol
	GetMarketData(ctx context.Context, in *GetMarketDataRequest, opts ...grpc.CallOption) (*GetMarketDataResponse, error)
	// GetAssetDetails retrieves detailed asset information
	GetAssetDetails(ctx context.Context, in *GetAssetDetailsRequest, opts ...grpc.CallOption) (*GetAssetDetailsResponse, error)
	// GetBatchMarketData retrieves market data for multiple symbols
	GetBatchMarketData(ctx context.Context, in *GetBatchMarketDataRequest, opts ...grpc.CallOption) (*GetBatchMarketDataResponse, error)
}

type marketDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketDataServiceClient(cc grpc.ClientConnInterface) MarketDataServiceClient {
	return &marketDataServiceClient{cc}
}

func (c *marketDataServiceClient) GetMarketData(ctx context.Context, in *GetMarketDataRequest, opts ...grpc.CallOption) (*GetMarketDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMarketDataResponse)
	err := c.cc.Invoke(ctx, MarketDataService_GetMarketData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketDataServiceClient) GetAssetDetails(ctx context.Context, in *GetAssetDetailsRequest, opts ...grpc.CallOption) (*GetAssetDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAssetDetailsResponse)
	err := c.cc.Invoke(ctx, MarketDataService_GetAssetDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketDataServiceClient) GetBatchMarketData(ctx context.Context, in *GetBatchMarketDataRequest, opts ...grpc.CallOption) (*GetBatchMarketDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBatchMarketDataResponse)
	err := c.cc.Invoke(ctx, MarketDataService_GetBatchMarketData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketDataServiceServer is the server API for MarketDataService service.
// All implementations must embed UnimplementedMarketDataServiceServer
// for forward compatibility.
//
// MarketDataService provides market data operations
type MarketDataServiceServer interface {
	// GetMarketData retrieves market data for a specific symbol
	GetMarketData(context.Context, *GetMarketDataRequest) (*GetMarketDataResponse, error)
	// GetAssetDetails retrieves detailed asset information
	GetAssetDetails(context.Context, *GetAssetDetailsRequest) (*GetAssetDetailsResponse, error)
	// GetBatchMarketData retrieves market data for multiple symbols
	GetBatchMarketData(context.Context, *GetBatchMarketDataRequest) (*GetBatchMarketDataResponse, error)
	mustEmbedUnimplementedMarketDataServiceServer()
}

// UnimplementedMarketDataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMarketDataServiceServer struct{}

func (UnimplementedMarketDataServiceServer) GetMarketData(context.Context, *GetMarketDataRequest) (*GetMarketDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMarketData not implemented")
}
func (UnimplementedMarketDataServiceServer) GetAssetDetails(context.Context, *GetAssetDetailsRequest) (*GetAssetDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAssetDetails not implemented")
}
func (UnimplementedMarketDataServiceServer) GetBatchMarketData(context.Context, *GetBatchMarketDataRequest) (*GetBatchMarketDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBatchMarketData not implemented")
}
func (UnimplementedMarketDataServiceServer) mustEmbedUnimplementedMarketDataServiceServer() {}
func (UnimplementedMarketDataServiceServer) testEmbeddedByValue()                           {}

// UnsafeMarketDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarketDataServiceServer will
// result in compilation errors.
type UnsafeMarketDataServiceServer interface {
	mustEmbedUnimplementedMarketDataServiceServer()
}

func RegisterMarketDataServiceServer(s grpc.ServiceRegistrar, srv MarketDataServiceServer) {
	// If the following call pancis, it indicates UnimplementedMarketDataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MarketDataService_ServiceDesc, srv)
}

func _MarketDataService_GetMarketData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMarketDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketDataServiceServer).GetMarketData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketDataService_GetMarketData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketDataServiceServer).GetMarketData(ctx, req.(*GetMarketDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketDataService_GetAssetDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAssetDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketDataServiceServer).GetAssetDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketDataService_GetAssetDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketDataServiceServer).GetAssetDetails(ctx, req.(*GetAssetDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketDataService_GetBatchMarketData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBatchMarketDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketDataServiceServer).GetBatchMarketData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketDataService_GetBatchMarketData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketDataServiceServer).GetBatchMarketData(ctx, req.(*GetBatchMarketDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MarketDataService_ServiceDesc is the grpc.ServiceDesc for MarketDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MarketDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hub_investments.MarketDataService",
	HandlerType: (*MarketDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMarketData",
			Handler:    _MarketDataService_GetMarketData_Handler,
		},
		{
			MethodName: "GetAssetDetails",
			Handler:    _MarketDataService_GetAssetDetails_Handler,
		},
		{
			MethodName: "GetBatchMarketData",
			Handler:    _MarketDataService_GetBatchMarketData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "market_data_service.proto",
}
