// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: order_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	OrderType     string                 `protobuf:"bytes,3,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"` // MARKET, LIMIT, STOP_LOSS, STOP_LIMIT
	OrderSide     string                 `protobuf:"bytes,4,opt,name=order_side,json=orderSide,proto3" json:"order_side,omitempty"` // BUY, SELL
	Quantity      float64                `protobuf:"fixed64,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         *float64               `protobuf:"fixed64,6,opt,name=price,proto3,oneof" json:"price,omitempty"` // Required for LIMIT orders
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitOrderRequest) Reset() {
	*x = SubmitOrderRequest{}
	mi := &file_order_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitOrderRequest) ProtoMessage() {}

func (x *SubmitOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitOrderRequest.ProtoReflect.Descriptor instead.
func (*SubmitOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_service_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SubmitOrderRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *SubmitOrderRequest) GetOrderType() string {
	if x != nil {
		return x.OrderType
	}
	return ""
}

func (x *SubmitOrderRequest) GetOrderSide() string {
	if x != nil {
		return x.OrderSide
	}
	return ""
}

func (x *SubmitOrderRequest) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *SubmitOrderRequest) GetPrice() float64 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

type SubmitOrderResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ApiResponse    *APIResponse           `protobuf:"bytes,1,opt,name=api_response,json=apiResponse,proto3" json:"api_response,omitempty"`
	OrderId        string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status         string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	EstimatedPrice *float64               `protobuf:"fixed64,4,opt,name=estimated_price,json=estimatedPrice,proto3,oneof" json:"estimated_price,omitempty"`
	EstimatedValue *float64               `protobuf:"fixed64,5,opt,name=estimated_value,json=estimatedValue,proto3,oneof" json:"estimated_value,omitempty"`
	MarketPrice    *float64               `protobuf:"fixed64,6,opt,name=market_price,json=marketPrice,proto3,oneof" json:"market_price,omitempty"`
	SubmittedAt    string                 `protobuf:"bytes,7,opt,name=submitted_at,json=submittedAt,proto3" json:"submitted_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubmitOrderResponse) Reset() {
	*x = SubmitOrderResponse{}
	mi := &file_order_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitOrderResponse) ProtoMessage() {}

func (x *SubmitOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitOrderResponse.ProtoReflect.Descriptor instead.
func (*SubmitOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_service_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitOrderResponse) GetApiResponse() *APIResponse {
	if x != nil {
		return x.ApiResponse
	}
	return nil
}

func (x *SubmitOrderResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *SubmitOrderResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SubmitOrderResponse) GetEstimatedPrice() float64 {
	if x != nil && x.EstimatedPrice != nil {
		return *x.EstimatedPrice
	}
	return 0
}

func (x *SubmitOrderResponse) GetEstimatedValue() float64 {
	if x != nil && x.EstimatedValue != nil {
		return *x.EstimatedValue
	}
	return 0
}

func (x *SubmitOrderResponse) GetMarketPrice() float64 {
	if x != nil && x.MarketPrice != nil {
		return *x.MarketPrice
	}
	return 0
}

func (x *SubmitOrderResponse) GetSubmittedAt() string {
	if x != nil {
		return x.SubmittedAt
	}
	return ""
}

type GetOrderDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderDetailsRequest) Reset() {
	*x = GetOrderDetailsRequest{}
	mi := &file_order_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderDetailsRequest) ProtoMessage() {}

func (x *GetOrderDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetOrderDetailsRequest) Descriptor() ([]byte, []int) {
	return file_order_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetOrderDetailsRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *GetOrderDetailsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetOrderDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiResponse   *APIResponse           `protobuf:"bytes,1,opt,name=api_response,json=apiResponse,proto3" json:"api_response,omitempty"`
	Order         *OrderDetails          `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderDetailsResponse) Reset() {
	*x = GetOrderDetailsResponse{}
	mi := &file_order_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderDetailsResponse) ProtoMessage() {}

func (x *GetOrderDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetOrderDetailsResponse) Descriptor() ([]byte, []int) {
	return file_order_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrderDetailsResponse) GetApiResponse() *APIResponse {
	if x != nil {
		return x.ApiResponse
	}
	return nil
}

func (x *GetOrderDetailsResponse) GetOrder() *OrderDetails {
	if x != nil {
		return x.Order
	}
	return nil
}

type GetOrderStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderStatusRequest) Reset() {
	*x = GetOrderStatusRequest{}
	mi := &file_order_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderStatusRequest) ProtoMessage() {}

func (x *GetOrderStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderStatusRequest.ProtoReflect.Descriptor instead.
func (*GetOrderStatusRequest) Descriptor() ([]byte, []int) {
	return file_order_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetOrderStatusRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *GetOrderStatusRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetOrderStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiResponse   *APIResponse           `protobuf:"bytes,1,opt,name=api_response,json=apiResponse,proto3" json:"api_response,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	StatusMessage string                 `protobuf:"bytes,4,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderStatusResponse) Reset() {
	*x = GetOrderStatusResponse{}
	mi := &file_order_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderStatusResponse) ProtoMessage() {}

func (x *GetOrderStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderStatusResponse.ProtoReflect.Descriptor instead.
func (*GetOrderStatusResponse) Descriptor() ([]byte, []int) {
	return file_order_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetOrderStatusResponse) GetApiResponse() *APIResponse {
	if x != nil {
		return x.ApiResponse
	}
	return nil
}

func (x *GetOrderStatusResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *GetOrderStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetOrderStatusResponse) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

func (x *GetOrderStatusResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_order_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_service_proto_rawDescGZIP(), []int{6}
}

func (x *CancelOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CancelOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CancelOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiResponse   *APIResponse           `protobuf:"bytes,1,opt,name=api_response,json=apiResponse,proto3" json:"api_response,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	CancelledAt   string                 `protobuf:"bytes,4,opt,name=cancelled_at,json=cancelledAt,proto3" json:"cancelled_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderResponse) Reset() {
	*x = CancelOrderResponse{}
	mi := &file_order_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderResponse) ProtoMessage() {}

func (x *CancelOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderResponse.ProtoReflect.Descriptor instead.
func (*CancelOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_service_proto_rawDescGZIP(), []int{7}
}

func (x *CancelOrderResponse) GetApiResponse() *APIResponse {
	if x != nil {
		return x.ApiResponse
	}
	return nil
}

func (x *CancelOrderResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CancelOrderResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CancelOrderResponse) GetCancelledAt() string {
	if x != nil {
		return x.CancelledAt
	}
	return ""
}

// OrderDetails contains complete order information
type OrderDetails struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	OrderId                 string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId                  string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Symbol                  string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	OrderType               string                 `protobuf:"bytes,4,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"`
	OrderSide               string                 `protobuf:"bytes,5,opt,name=order_side,json=orderSide,proto3" json:"order_side,omitempty"`
	Quantity                float64                `protobuf:"fixed64,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price                   *float64               `protobuf:"fixed64,7,opt,name=price,proto3,oneof" json:"price,omitempty"`
	Status                  string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt               string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt               string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ExecutedAt              *string                `protobuf:"bytes,11,opt,name=executed_at,json=executedAt,proto3,oneof" json:"executed_at,omitempty"`
	ExecutionPrice          *float64               `protobuf:"fixed64,12,opt,name=execution_price,json=executionPrice,proto3,oneof" json:"execution_price,omitempty"`
	MarketPriceAtSubmission *float64               `protobuf:"fixed64,13,opt,name=market_price_at_submission,json=marketPriceAtSubmission,proto3,oneof" json:"market_price_at_submission,omitempty"`
	MarketDataTimestamp     *string                `protobuf:"bytes,14,opt,name=market_data_timestamp,json=marketDataTimestamp,proto3,oneof" json:"market_data_timestamp,omitempty"`
	EstimatedValue          float64                `protobuf:"fixed64,15,opt,name=estimated_value,json=estimatedValue,proto3" json:"estimated_value,omitempty"`
	ExecutionValue          *float64               `protobuf:"fixed64,16,opt,name=execution_value,json=executionValue,proto3,oneof" json:"execution_value,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *OrderDetails) Reset() {
	*x = OrderDetails{}
	mi := &file_order_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDetails) ProtoMessage() {}

func (x *OrderDetails) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDetails.ProtoReflect.Descriptor instead.
func (*OrderDetails) Descriptor() ([]byte, []int) {
	return file_order_service_proto_rawDescGZIP(), []int{8}
}

func (x *OrderDetails) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderDetails) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OrderDetails) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *OrderDetails) GetOrderType() string {
	if x != nil {
		return x.OrderType
	}
	return ""
}

func (x *OrderDetails) GetOrderSide() string {
	if x != nil {
		return x.OrderSide
	}
	return ""
}

func (x *OrderDetails) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderDetails) GetPrice() float64 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

func (x *OrderDetails) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrderDetails) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *OrderDetails) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *OrderDetails) GetExecutedAt() string {
	if x != nil && x.ExecutedAt != nil {
		return *x.ExecutedAt
	}
	return ""
}

func (x *OrderDetails) GetExecutionPrice() float64 {
	if x != nil && x.ExecutionPrice != nil {
		return *x.ExecutionPrice
	}
	return 0
}

func (x *OrderDetails) GetMarketPriceAtSubmission() float64 {
	if x != nil && x.MarketPriceAtSubmission != nil {
		return *x.MarketPriceAtSubmission
	}
	return 0
}

func (x *OrderDetails) GetMarketDataTimestamp() string {
	if x != nil && x.MarketDataTimestamp != nil {
		return *x.MarketDataTimestamp
	}
	return ""
}

func (x *OrderDetails) GetEstimatedValue() float64 {
	if x != nil {
		return x.EstimatedValue
	}
	return 0
}

func (x *OrderDetails) GetExecutionValue() float64 {
	if x != nil && x.ExecutionValue != nil {
		return *x.ExecutionValue
	}
	return 0
}

var File_order_service_proto protoreflect.FileDescriptor

const file_order_service_proto_rawDesc = "" +
	"\n" +
	"\x13order_service.proto\x12\x0fhub_investments\x1a\fcommon.proto\"\xc4\x01\n" +
	"\x12SubmitOrderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x1d\n" +
	"\n" +
	"order_type\x18\x03 \x01(\tR\torderType\x12\x1d\n" +
	"\n" +
	"order_side\x18\x04 \x01(\tR\torderSide\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x01R\bquantity\x12\x19\n" +
	"\x05price\x18\x06 \x01(\x01H\x00R\x05price\x88\x01\x01B\b\n" +
	"\x06_price\"\xe9\x02\n" +
	"\x13SubmitOrderResponse\x12?\n" +
	"\fapi_response\x18\x01 \x01(\v2\x1c.hub_investments.APIResponseR\vapiResponse\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12,\n" +
	"\x0festimated_price\x18\x04 \x01(\x01H\x00R\x0eestimatedPrice\x88\x01\x01\x12,\n" +
	"\x0festimated_value\x18\x05 \x01(\x01H\x01R\x0eestimatedValue\x88\x01\x01\x12&\n" +
	"\fmarket_price\x18\x06 \x01(\x01H\x02R\vmarketPrice\x88\x01\x01\x12!\n" +
	"\fsubmitted_at\x18\a \x01(\tR\vsubmittedAtB\x12\n" +
	"\x10_estimated_priceB\x12\n" +
	"\x10_estimated_valueB\x0f\n" +
	"\r_market_price\"L\n" +
	"\x16GetOrderDetailsRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x8f\x01\n" +
	"\x17GetOrderDetailsResponse\x12?\n" +
	"\fapi_response\x18\x01 \x01(\v2\x1c.hub_investments.APIResponseR\vapiResponse\x123\n" +
	"\x05order\x18\x02 \x01(\v2\x1d.hub_investments.OrderDetailsR\x05order\"K\n" +
	"\x15GetOrderStatusRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\xd2\x01\n" +
	"\x16GetOrderStatusResponse\x12?\n" +
	"\fapi_response\x18\x01 \x01(\v2\x1c.hub_investments.APIResponseR\vapiResponse\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12%\n" +
	"\x0estatus_message\x18\x04 \x01(\tR\rstatusMessage\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\"H\n" +
	"\x12CancelOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\xac\x01\n" +
	"\x13CancelOrderResponse\x12?\n" +
	"\fapi_response\x18\x01 \x01(\v2\x1c.hub_investments.APIResponseR\vapiResponse\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12!\n" +
	"\fcancelled_at\x18\x04 \x01(\tR\vcancelledAt\"\xc6\x05\n" +
	"\fOrderDetails\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\x1d\n" +
	"\n" +
	"order_type\x18\x04 \x01(\tR\torderType\x12\x1d\n" +
	"\n" +
	"order_side\x18\x05 \x01(\tR\torderSide\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x01R\bquantity\x12\x19\n" +
	"\x05price\x18\a \x01(\x01H\x00R\x05price\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\x12$\n" +
	"\vexecuted_at\x18\v \x01(\tH\x01R\n" +
	"executedAt\x88\x01\x01\x12,\n" +
	"\x0fexecution_price\x18\f \x01(\x01H\x02R\x0eexecutionPrice\x88\x01\x01\x12@\n" +
	"\x1amarket_price_at_submission\x18\r \x01(\x01H\x03R\x17marketPriceAtSubmission\x88\x01\x01\x127\n" +
	"\x15market_data_timestamp\x18\x0e \x01(\tH\x04R\x13marketDataTimestamp\x88\x01\x01\x12'\n" +
	"\x0festimated_value\x18\x0f \x01(\x01R\x0eestimatedValue\x12,\n" +
	"\x0fexecution_value\x18\x10 \x01(\x01H\x05R\x0eexecutionValue\x88\x01\x01B\b\n" +
	"\x06_priceB\x0e\n" +
	"\f_executed_atB\x12\n" +
	"\x10_execution_priceB\x1d\n" +
	"\x1b_market_price_at_submissionB\x18\n" +
	"\x16_market_data_timestampB\x12\n" +
	"\x10_execution_value2\x8b\x03\n" +
	"\fOrderService\x12X\n" +
	"\vSubmitOrder\x12#.hub_investments.SubmitOrderRequest\x1a$.hub_investments.SubmitOrderResponse\x12d\n" +
	"\x0fGetOrderDetails\x12'.hub_investments.GetOrderDetailsRequest\x1a(.hub_investments.GetOrderDetailsResponse\x12a\n" +
	"\x0eGetOrderStatus\x12&.hub_investments.GetOrderStatusRequest\x1a'.hub_investments.GetOrderStatusResponse\x12X\n" +
	"\vCancelOrder\x12#.hub_investments.CancelOrderRequest\x1a$.hub_investments.CancelOrderResponseB\tZ\a./protob\x06proto3"

var (
	file_order_service_proto_rawDescOnce sync.Once
	file_order_service_proto_rawDescData []byte
)

func file_order_service_proto_rawDescGZIP() []byte {
	file_order_service_proto_rawDescOnce.Do(func() {
		file_order_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_service_proto_rawDesc), len(file_order_service_proto_rawDesc)))
	})
	return file_order_service_proto_rawDescData
}

var file_order_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_order_service_proto_goTypes = []any{
	(*SubmitOrderRequest)(nil),      // 0: hub_investments.SubmitOrderRequest
	(*SubmitOrderResponse)(nil),     // 1: hub_investments.SubmitOrderResponse
	(*GetOrderDetailsRequest)(nil),  // 2: hub_investments.GetOrderDetailsRequest
	(*GetOrderDetailsResponse)(nil), // 3: hub_investments.GetOrderDetailsResponse
	(*GetOrderStatusRequest)(nil),   // 4: hub_investments.GetOrderStatusRequest
	(*GetOrderStatusResponse)(nil),  // 5: hub_investments.GetOrderStatusResponse
	(*CancelOrderRequest)(nil),      // 6: hub_investments.CancelOrderRequest
	(*CancelOrderResponse)(nil),     // 7: hub_investments.CancelOrderResponse
	(*OrderDetails)(nil),            // 8: hub_investments.OrderDetails
	(*APIResponse)(nil),             // 9: hub_investments.APIResponse
}
var file_order_service_proto_depIdxs = []int32{
	9, // 0: hub_investments.SubmitOrderResponse.api_response:type_name -> hub_investments.APIResponse
	9, // 1: hub_investments.GetOrderDetailsResponse.api_response:type_name -> hub_investments.APIResponse
	8, // 2: hub_investments.GetOrderDetailsResponse.order:type_name -> hub_investments.OrderDetails
	9, // 3: hub_investments.GetOrderStatusResponse.api_response:type_name -> hub_investments.APIResponse
	9, // 4: hub_investments.CancelOrderResponse.api_response:type_name -> hub_investments.APIResponse
	0, // 5: hub_investments.OrderService.SubmitOrder:input_type -> hub_investments.SubmitOrderRequest
	2, // 6: hub_investments.OrderService.GetOrderDetails:input_type -> hub_investments.GetOrderDetailsRequest
	4, // 7: hub_investments.OrderService.GetOrderStatus:input_type -> hub_investments.GetOrderStatusRequest
	6, // 8: hub_investments.OrderService.CancelOrder:input_type -> hub_investments.CancelOrderRequest
	1, // 9: hub_investments.OrderService.SubmitOrder:output_type -> hub_investments.SubmitOrderResponse
	3, // 10: hub_investments.OrderService.GetOrderDetails:output_type -> hub_investments.GetOrderDetailsResponse
	5, // 11: hub_investments.OrderService.GetOrderStatus:output_type -> hub_investments.GetOrderStatusResponse
	7, // 12: hub_investments.OrderService.CancelOrder:output_type -> hub_investments.CancelOrderResponse
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_order_service_proto_init() }
func file_order_service_proto_init() {
	if File_order_service_proto != nil {
		return
	}
	file_common_proto_init()
	file_order_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_order_service_proto_msgTypes[1].OneofWrappers = []any{}
	file_order_service_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_service_proto_rawDesc), len(file_order_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_service_proto_goTypes,
		DependencyIndexes: file_order_service_proto_depIdxs,
		MessageInfos:      file_order_service_proto_msgTypes,
	}.Build()
	File_order_service_proto = out.File
	file_order_service_proto_goTypes = nil
	file_order_service_proto_depIdxs = nil
}
