// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: portfolio_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPortfolioSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPortfolioSummaryRequest) Reset() {
	*x = GetPortfolioSummaryRequest{}
	mi := &file_portfolio_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPortfolioSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPortfolioSummaryRequest) ProtoMessage() {}

func (x *GetPortfolioSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPortfolioSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetPortfolioSummaryRequest) Descriptor() ([]byte, []int) {
	return file_portfolio_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetPortfolioSummaryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetPortfolioSummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiResponse   *APIResponse           `protobuf:"bytes,1,opt,name=api_response,json=apiResponse,proto3" json:"api_response,omitempty"`
	Portfolio     *PortfolioSummary      `protobuf:"bytes,2,opt,name=portfolio,proto3" json:"portfolio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPortfolioSummaryResponse) Reset() {
	*x = GetPortfolioSummaryResponse{}
	mi := &file_portfolio_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPortfolioSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPortfolioSummaryResponse) ProtoMessage() {}

func (x *GetPortfolioSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPortfolioSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetPortfolioSummaryResponse) Descriptor() ([]byte, []int) {
	return file_portfolio_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetPortfolioSummaryResponse) GetApiResponse() *APIResponse {
	if x != nil {
		return x.ApiResponse
	}
	return nil
}

func (x *GetPortfolioSummaryResponse) GetPortfolio() *PortfolioSummary {
	if x != nil {
		return x.Portfolio
	}
	return nil
}

type PortfolioSummary struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	TotalBalance              float64                `protobuf:"fixed64,1,opt,name=total_balance,json=totalBalance,proto3" json:"total_balance,omitempty"`
	TotalInvested             float64                `protobuf:"fixed64,2,opt,name=total_invested,json=totalInvested,proto3" json:"total_invested,omitempty"`
	TotalCurrentValue         float64                `protobuf:"fixed64,3,opt,name=total_current_value,json=totalCurrentValue,proto3" json:"total_current_value,omitempty"`
	TotalProfitLoss           float64                `protobuf:"fixed64,4,opt,name=total_profit_loss,json=totalProfitLoss,proto3" json:"total_profit_loss,omitempty"`
	TotalProfitLossPercentage float64                `protobuf:"fixed64,5,opt,name=total_profit_loss_percentage,json=totalProfitLossPercentage,proto3" json:"total_profit_loss_percentage,omitempty"`
	Positions                 []*PortfolioPosition   `protobuf:"bytes,6,rep,name=positions,proto3" json:"positions,omitempty"`
	LastUpdated               string                 `protobuf:"bytes,7,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *PortfolioSummary) Reset() {
	*x = PortfolioSummary{}
	mi := &file_portfolio_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortfolioSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortfolioSummary) ProtoMessage() {}

func (x *PortfolioSummary) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortfolioSummary.ProtoReflect.Descriptor instead.
func (*PortfolioSummary) Descriptor() ([]byte, []int) {
	return file_portfolio_service_proto_rawDescGZIP(), []int{2}
}

func (x *PortfolioSummary) GetTotalBalance() float64 {
	if x != nil {
		return x.TotalBalance
	}
	return 0
}

func (x *PortfolioSummary) GetTotalInvested() float64 {
	if x != nil {
		return x.TotalInvested
	}
	return 0
}

func (x *PortfolioSummary) GetTotalCurrentValue() float64 {
	if x != nil {
		return x.TotalCurrentValue
	}
	return 0
}

func (x *PortfolioSummary) GetTotalProfitLoss() float64 {
	if x != nil {
		return x.TotalProfitLoss
	}
	return 0
}

func (x *PortfolioSummary) GetTotalProfitLossPercentage() float64 {
	if x != nil {
		return x.TotalProfitLossPercentage
	}
	return 0
}

func (x *PortfolioSummary) GetPositions() []*PortfolioPosition {
	if x != nil {
		return x.Positions
	}
	return nil
}

func (x *PortfolioSummary) GetLastUpdated() string {
	if x != nil {
		return x.LastUpdated
	}
	return ""
}

type PortfolioPosition struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Symbol               string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	CompanyName          string                 `protobuf:"bytes,4,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	Quantity             float64                `protobuf:"fixed64,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	AveragePrice         float64                `protobuf:"fixed64,6,opt,name=average_price,json=averagePrice,proto3" json:"average_price,omitempty"`
	CurrentPrice         float64                `protobuf:"fixed64,7,opt,name=current_price,json=currentPrice,proto3" json:"current_price,omitempty"`
	TotalInvested        float64                `protobuf:"fixed64,8,opt,name=total_invested,json=totalInvested,proto3" json:"total_invested,omitempty"`
	CurrentValue         float64                `protobuf:"fixed64,9,opt,name=current_value,json=currentValue,proto3" json:"current_value,omitempty"`
	ProfitLoss           float64                `protobuf:"fixed64,10,opt,name=profit_loss,json=profitLoss,proto3" json:"profit_loss,omitempty"`
	ProfitLossPercentage float64                `protobuf:"fixed64,11,opt,name=profit_loss_percentage,json=profitLossPercentage,proto3" json:"profit_loss_percentage,omitempty"`
	LastUpdated          string                 `protobuf:"bytes,12,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PortfolioPosition) Reset() {
	*x = PortfolioPosition{}
	mi := &file_portfolio_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortfolioPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortfolioPosition) ProtoMessage() {}

func (x *PortfolioPosition) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortfolioPosition.ProtoReflect.Descriptor instead.
func (*PortfolioPosition) Descriptor() ([]byte, []int) {
	return file_portfolio_service_proto_rawDescGZIP(), []int{3}
}

func (x *PortfolioPosition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PortfolioPosition) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PortfolioPosition) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *PortfolioPosition) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *PortfolioPosition) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *PortfolioPosition) GetAveragePrice() float64 {
	if x != nil {
		return x.AveragePrice
	}
	return 0
}

func (x *PortfolioPosition) GetCurrentPrice() float64 {
	if x != nil {
		return x.CurrentPrice
	}
	return 0
}

func (x *PortfolioPosition) GetTotalInvested() float64 {
	if x != nil {
		return x.TotalInvested
	}
	return 0
}

func (x *PortfolioPosition) GetCurrentValue() float64 {
	if x != nil {
		return x.CurrentValue
	}
	return 0
}

func (x *PortfolioPosition) GetProfitLoss() float64 {
	if x != nil {
		return x.ProfitLoss
	}
	return 0
}

func (x *PortfolioPosition) GetProfitLossPercentage() float64 {
	if x != nil {
		return x.ProfitLossPercentage
	}
	return 0
}

func (x *PortfolioPosition) GetLastUpdated() string {
	if x != nil {
		return x.LastUpdated
	}
	return ""
}

var File_portfolio_service_proto protoreflect.FileDescriptor

const file_portfolio_service_proto_rawDesc = "" +
	"\n" +
	"\x17portfolio_service.proto\x12\x0fhub_investments\x1a\fcommon.proto\"5\n" +
	"\x1aGetPortfolioSummaryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x9f\x01\n" +
	"\x1bGetPortfolioSummaryResponse\x12?\n" +
	"\fapi_response\x18\x01 \x01(\v2\x1c.hub_investments.APIResponseR\vapiResponse\x12?\n" +
	"\tportfolio\x18\x02 \x01(\v2!.hub_investments.PortfolioSummaryR\tportfolio\"\xe0\x02\n" +
	"\x10PortfolioSummary\x12#\n" +
	"\rtotal_balance\x18\x01 \x01(\x01R\ftotalBalance\x12%\n" +
	"\x0etotal_invested\x18\x02 \x01(\x01R\rtotalInvested\x12.\n" +
	"\x13total_current_value\x18\x03 \x01(\x01R\x11totalCurrentValue\x12*\n" +
	"\x11total_profit_loss\x18\x04 \x01(\x01R\x0ftotalProfitLoss\x12?\n" +
	"\x1ctotal_profit_loss_percentage\x18\x05 \x01(\x01R\x19totalProfitLossPercentage\x12@\n" +
	"\tpositions\x18\x06 \x03(\v2\".hub_investments.PortfolioPositionR\tpositions\x12!\n" +
	"\flast_updated\x18\a \x01(\tR\vlastUpdated\"\xa3\x03\n" +
	"\x11PortfolioPosition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12!\n" +
	"\fcompany_name\x18\x04 \x01(\tR\vcompanyName\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x01R\bquantity\x12#\n" +
	"\raverage_price\x18\x06 \x01(\x01R\faveragePrice\x12#\n" +
	"\rcurrent_price\x18\a \x01(\x01R\fcurrentPrice\x12%\n" +
	"\x0etotal_invested\x18\b \x01(\x01R\rtotalInvested\x12#\n" +
	"\rcurrent_value\x18\t \x01(\x01R\fcurrentValue\x12\x1f\n" +
	"\vprofit_loss\x18\n" +
	" \x01(\x01R\n" +
	"profitLoss\x124\n" +
	"\x16profit_loss_percentage\x18\v \x01(\x01R\x14profitLossPercentage\x12!\n" +
	"\flast_updated\x18\f \x01(\tR\vlastUpdated2\x84\x01\n" +
	"\x10PortfolioService\x12p\n" +
	"\x13GetPortfolioSummary\x12+.hub_investments.GetPortfolioSummaryRequest\x1a,.hub_investments.GetPortfolioSummaryResponseB\tZ\a./protob\x06proto3"

var (
	file_portfolio_service_proto_rawDescOnce sync.Once
	file_portfolio_service_proto_rawDescData []byte
)

func file_portfolio_service_proto_rawDescGZIP() []byte {
	file_portfolio_service_proto_rawDescOnce.Do(func() {
		file_portfolio_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_portfolio_service_proto_rawDesc), len(file_portfolio_service_proto_rawDesc)))
	})
	return file_portfolio_service_proto_rawDescData
}

var file_portfolio_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_portfolio_service_proto_goTypes = []any{
	(*GetPortfolioSummaryRequest)(nil),  // 0: hub_investments.GetPortfolioSummaryRequest
	(*GetPortfolioSummaryResponse)(nil), // 1: hub_investments.GetPortfolioSummaryResponse
	(*PortfolioSummary)(nil),            // 2: hub_investments.PortfolioSummary
	(*PortfolioPosition)(nil),           // 3: hub_investments.PortfolioPosition
	(*APIResponse)(nil),                 // 4: hub_investments.APIResponse
}
var file_portfolio_service_proto_depIdxs = []int32{
	4, // 0: hub_investments.GetPortfolioSummaryResponse.api_response:type_name -> hub_investments.APIResponse
	2, // 1: hub_investments.GetPortfolioSummaryResponse.portfolio:type_name -> hub_investments.PortfolioSummary
	3, // 2: hub_investments.PortfolioSummary.positions:type_name -> hub_investments.PortfolioPosition
	0, // 3: hub_investments.PortfolioService.GetPortfolioSummary:input_type -> hub_investments.GetPortfolioSummaryRequest
	1, // 4: hub_investments.PortfolioService.GetPortfolioSummary:output_type -> hub_investments.GetPortfolioSummaryResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_portfolio_service_proto_init() }
func file_portfolio_service_proto_init() {
	if File_portfolio_service_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_portfolio_service_proto_rawDesc), len(file_portfolio_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_portfolio_service_proto_goTypes,
		DependencyIndexes: file_portfolio_service_proto_depIdxs,
		MessageInfos:      file_portfolio_service_proto_msgTypes,
	}.Build()
	File_portfolio_service_proto = out.File
	file_portfolio_service_proto_goTypes = nil
	file_portfolio_service_proto_depIdxs = nil
}
