// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: position_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPositionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Symbol        *string                `protobuf:"bytes,2,opt,name=symbol,proto3,oneof" json:"symbol,omitempty"` // Filter by symbol if provided
	Status        *string                `protobuf:"bytes,3,opt,name=status,proto3,oneof" json:"status,omitempty"` // Filter by status if provided
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPositionsRequest) Reset() {
	*x = GetPositionsRequest{}
	mi := &file_position_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPositionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPositionsRequest) ProtoMessage() {}

func (x *GetPositionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_position_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPositionsRequest.ProtoReflect.Descriptor instead.
func (*GetPositionsRequest) Descriptor() ([]byte, []int) {
	return file_position_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetPositionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetPositionsRequest) GetSymbol() string {
	if x != nil && x.Symbol != nil {
		return *x.Symbol
	}
	return ""
}

func (x *GetPositionsRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

type GetPositionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiResponse   *APIResponse           `protobuf:"bytes,1,opt,name=api_response,json=apiResponse,proto3" json:"api_response,omitempty"`
	Positions     []*Position            `protobuf:"bytes,2,rep,name=positions,proto3" json:"positions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPositionsResponse) Reset() {
	*x = GetPositionsResponse{}
	mi := &file_position_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPositionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPositionsResponse) ProtoMessage() {}

func (x *GetPositionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_position_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPositionsResponse.ProtoReflect.Descriptor instead.
func (*GetPositionsResponse) Descriptor() ([]byte, []int) {
	return file_position_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetPositionsResponse) GetApiResponse() *APIResponse {
	if x != nil {
		return x.ApiResponse
	}
	return nil
}

func (x *GetPositionsResponse) GetPositions() []*Position {
	if x != nil {
		return x.Positions
	}
	return nil
}

type GetPositionAggregationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPositionAggregationRequest) Reset() {
	*x = GetPositionAggregationRequest{}
	mi := &file_position_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPositionAggregationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPositionAggregationRequest) ProtoMessage() {}

func (x *GetPositionAggregationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_position_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPositionAggregationRequest.ProtoReflect.Descriptor instead.
func (*GetPositionAggregationRequest) Descriptor() ([]byte, []int) {
	return file_position_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetPositionAggregationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetPositionAggregationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiResponse   *APIResponse           `protobuf:"bytes,1,opt,name=api_response,json=apiResponse,proto3" json:"api_response,omitempty"`
	Aggregation   *PositionAggregation   `protobuf:"bytes,2,opt,name=aggregation,proto3" json:"aggregation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPositionAggregationResponse) Reset() {
	*x = GetPositionAggregationResponse{}
	mi := &file_position_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPositionAggregationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPositionAggregationResponse) ProtoMessage() {}

func (x *GetPositionAggregationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_position_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPositionAggregationResponse.ProtoReflect.Descriptor instead.
func (*GetPositionAggregationResponse) Descriptor() ([]byte, []int) {
	return file_position_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetPositionAggregationResponse) GetApiResponse() *APIResponse {
	if x != nil {
		return x.ApiResponse
	}
	return nil
}

func (x *GetPositionAggregationResponse) GetAggregation() *PositionAggregation {
	if x != nil {
		return x.Aggregation
	}
	return nil
}

type CreatePositionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Quantity      float64                `protobuf:"fixed64,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	PositionType  string                 `protobuf:"bytes,5,opt,name=position_type,json=positionType,proto3" json:"position_type,omitempty"` // LONG, SHORT
	SourceOrderId *string                `protobuf:"bytes,6,opt,name=source_order_id,json=sourceOrderId,proto3,oneof" json:"source_order_id,omitempty"`
	CreatedFrom   *string                `protobuf:"bytes,7,opt,name=created_from,json=createdFrom,proto3,oneof" json:"created_from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePositionRequest) Reset() {
	*x = CreatePositionRequest{}
	mi := &file_position_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePositionRequest) ProtoMessage() {}

func (x *CreatePositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_position_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePositionRequest.ProtoReflect.Descriptor instead.
func (*CreatePositionRequest) Descriptor() ([]byte, []int) {
	return file_position_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePositionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreatePositionRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *CreatePositionRequest) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CreatePositionRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreatePositionRequest) GetPositionType() string {
	if x != nil {
		return x.PositionType
	}
	return ""
}

func (x *CreatePositionRequest) GetSourceOrderId() string {
	if x != nil && x.SourceOrderId != nil {
		return *x.SourceOrderId
	}
	return ""
}

func (x *CreatePositionRequest) GetCreatedFrom() string {
	if x != nil && x.CreatedFrom != nil {
		return *x.CreatedFrom
	}
	return ""
}

type CreatePositionResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ApiResponse     *APIResponse           `protobuf:"bytes,1,opt,name=api_response,json=apiResponse,proto3" json:"api_response,omitempty"`
	PositionId      string                 `protobuf:"bytes,2,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"`
	Status          string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	TotalInvestment float64                `protobuf:"fixed64,4,opt,name=total_investment,json=totalInvestment,proto3" json:"total_investment,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreatePositionResponse) Reset() {
	*x = CreatePositionResponse{}
	mi := &file_position_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePositionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePositionResponse) ProtoMessage() {}

func (x *CreatePositionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_position_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePositionResponse.ProtoReflect.Descriptor instead.
func (*CreatePositionResponse) Descriptor() ([]byte, []int) {
	return file_position_service_proto_rawDescGZIP(), []int{5}
}

func (x *CreatePositionResponse) GetApiResponse() *APIResponse {
	if x != nil {
		return x.ApiResponse
	}
	return nil
}

func (x *CreatePositionResponse) GetPositionId() string {
	if x != nil {
		return x.PositionId
	}
	return ""
}

func (x *CreatePositionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreatePositionResponse) GetTotalInvestment() float64 {
	if x != nil {
		return x.TotalInvestment
	}
	return 0
}

type UpdatePositionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PositionId    string                 `protobuf:"bytes,1,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TradeQuantity float64                `protobuf:"fixed64,3,opt,name=trade_quantity,json=tradeQuantity,proto3" json:"trade_quantity,omitempty"`
	TradePrice    float64                `protobuf:"fixed64,4,opt,name=trade_price,json=tradePrice,proto3" json:"trade_price,omitempty"`
	IsBuyOrder    bool                   `protobuf:"varint,5,opt,name=is_buy_order,json=isBuyOrder,proto3" json:"is_buy_order,omitempty"`
	SourceOrderId *string                `protobuf:"bytes,6,opt,name=source_order_id,json=sourceOrderId,proto3,oneof" json:"source_order_id,omitempty"`
	ExecutionTime *string                `protobuf:"bytes,7,opt,name=execution_time,json=executionTime,proto3,oneof" json:"execution_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePositionRequest) Reset() {
	*x = UpdatePositionRequest{}
	mi := &file_position_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePositionRequest) ProtoMessage() {}

func (x *UpdatePositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_position_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePositionRequest.ProtoReflect.Descriptor instead.
func (*UpdatePositionRequest) Descriptor() ([]byte, []int) {
	return file_position_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdatePositionRequest) GetPositionId() string {
	if x != nil {
		return x.PositionId
	}
	return ""
}

func (x *UpdatePositionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdatePositionRequest) GetTradeQuantity() float64 {
	if x != nil {
		return x.TradeQuantity
	}
	return 0
}

func (x *UpdatePositionRequest) GetTradePrice() float64 {
	if x != nil {
		return x.TradePrice
	}
	return 0
}

func (x *UpdatePositionRequest) GetIsBuyOrder() bool {
	if x != nil {
		return x.IsBuyOrder
	}
	return false
}

func (x *UpdatePositionRequest) GetSourceOrderId() string {
	if x != nil && x.SourceOrderId != nil {
		return *x.SourceOrderId
	}
	return ""
}

func (x *UpdatePositionRequest) GetExecutionTime() string {
	if x != nil && x.ExecutionTime != nil {
		return *x.ExecutionTime
	}
	return ""
}

type UpdatePositionResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ApiResponse        *APIResponse           `protobuf:"bytes,1,opt,name=api_response,json=apiResponse,proto3" json:"api_response,omitempty"`
	PositionId         string                 `protobuf:"bytes,2,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"`
	NewQuantity        float64                `protobuf:"fixed64,3,opt,name=new_quantity,json=newQuantity,proto3" json:"new_quantity,omitempty"`
	NewAveragePrice    float64                `protobuf:"fixed64,4,opt,name=new_average_price,json=newAveragePrice,proto3" json:"new_average_price,omitempty"`
	NewTotalInvestment float64                `protobuf:"fixed64,5,opt,name=new_total_investment,json=newTotalInvestment,proto3" json:"new_total_investment,omitempty"`
	Status             string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	TransactionType    string                 `protobuf:"bytes,7,opt,name=transaction_type,json=transactionType,proto3" json:"transaction_type,omitempty"`
	RealizedPnl        *float64               `protobuf:"fixed64,8,opt,name=realized_pnl,json=realizedPnl,proto3,oneof" json:"realized_pnl,omitempty"`
	RealizedPnlPct     *float64               `protobuf:"fixed64,9,opt,name=realized_pnl_pct,json=realizedPnlPct,proto3,oneof" json:"realized_pnl_pct,omitempty"`
	EventsPublished    int32                  `protobuf:"varint,10,opt,name=events_published,json=eventsPublished,proto3" json:"events_published,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdatePositionResponse) Reset() {
	*x = UpdatePositionResponse{}
	mi := &file_position_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePositionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePositionResponse) ProtoMessage() {}

func (x *UpdatePositionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_position_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePositionResponse.ProtoReflect.Descriptor instead.
func (*UpdatePositionResponse) Descriptor() ([]byte, []int) {
	return file_position_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdatePositionResponse) GetApiResponse() *APIResponse {
	if x != nil {
		return x.ApiResponse
	}
	return nil
}

func (x *UpdatePositionResponse) GetPositionId() string {
	if x != nil {
		return x.PositionId
	}
	return ""
}

func (x *UpdatePositionResponse) GetNewQuantity() float64 {
	if x != nil {
		return x.NewQuantity
	}
	return 0
}

func (x *UpdatePositionResponse) GetNewAveragePrice() float64 {
	if x != nil {
		return x.NewAveragePrice
	}
	return 0
}

func (x *UpdatePositionResponse) GetNewTotalInvestment() float64 {
	if x != nil {
		return x.NewTotalInvestment
	}
	return 0
}

func (x *UpdatePositionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdatePositionResponse) GetTransactionType() string {
	if x != nil {
		return x.TransactionType
	}
	return ""
}

func (x *UpdatePositionResponse) GetRealizedPnl() float64 {
	if x != nil && x.RealizedPnl != nil {
		return *x.RealizedPnl
	}
	return 0
}

func (x *UpdatePositionResponse) GetRealizedPnlPct() float64 {
	if x != nil && x.RealizedPnlPct != nil {
		return *x.RealizedPnlPct
	}
	return 0
}

func (x *UpdatePositionResponse) GetEventsPublished() int32 {
	if x != nil {
		return x.EventsPublished
	}
	return 0
}

// Position contains position information
type Position struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PositionId       string                 `protobuf:"bytes,1,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"`
	UserId           string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Symbol           string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Quantity         float64                `protobuf:"fixed64,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	AveragePrice     float64                `protobuf:"fixed64,5,opt,name=average_price,json=averagePrice,proto3" json:"average_price,omitempty"`
	TotalInvestment  float64                `protobuf:"fixed64,6,opt,name=total_investment,json=totalInvestment,proto3" json:"total_investment,omitempty"`
	CurrentPrice     float64                `protobuf:"fixed64,7,opt,name=current_price,json=currentPrice,proto3" json:"current_price,omitempty"`
	MarketValue      float64                `protobuf:"fixed64,8,opt,name=market_value,json=marketValue,proto3" json:"market_value,omitempty"`
	UnrealizedPnl    float64                `protobuf:"fixed64,9,opt,name=unrealized_pnl,json=unrealizedPnl,proto3" json:"unrealized_pnl,omitempty"`
	UnrealizedPnlPct float64                `protobuf:"fixed64,10,opt,name=unrealized_pnl_pct,json=unrealizedPnlPct,proto3" json:"unrealized_pnl_pct,omitempty"`
	PositionType     string                 `protobuf:"bytes,11,opt,name=position_type,json=positionType,proto3" json:"position_type,omitempty"` // LONG, SHORT
	Status           string                 `protobuf:"bytes,12,opt,name=status,proto3" json:"status,omitempty"`                                 // ACTIVE, PARTIAL, CLOSED
	CreatedAt        string                 `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        string                 `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	LastTradeAt      *string                `protobuf:"bytes,15,opt,name=last_trade_at,json=lastTradeAt,proto3,oneof" json:"last_trade_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_position_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_position_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_position_service_proto_rawDescGZIP(), []int{8}
}

func (x *Position) GetPositionId() string {
	if x != nil {
		return x.PositionId
	}
	return ""
}

func (x *Position) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Position) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Position) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Position) GetAveragePrice() float64 {
	if x != nil {
		return x.AveragePrice
	}
	return 0
}

func (x *Position) GetTotalInvestment() float64 {
	if x != nil {
		return x.TotalInvestment
	}
	return 0
}

func (x *Position) GetCurrentPrice() float64 {
	if x != nil {
		return x.CurrentPrice
	}
	return 0
}

func (x *Position) GetMarketValue() float64 {
	if x != nil {
		return x.MarketValue
	}
	return 0
}

func (x *Position) GetUnrealizedPnl() float64 {
	if x != nil {
		return x.UnrealizedPnl
	}
	return 0
}

func (x *Position) GetUnrealizedPnlPct() float64 {
	if x != nil {
		return x.UnrealizedPnlPct
	}
	return 0
}

func (x *Position) GetPositionType() string {
	if x != nil {
		return x.PositionType
	}
	return ""
}

func (x *Position) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Position) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Position) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Position) GetLastTradeAt() string {
	if x != nil && x.LastTradeAt != nil {
		return *x.LastTradeAt
	}
	return ""
}

// PositionAggregation contains aggregated position data
type PositionAggregation struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	TotalInvested         float64                `protobuf:"fixed64,1,opt,name=total_invested,json=totalInvested,proto3" json:"total_invested,omitempty"`
	TotalCurrentValue     float64                `protobuf:"fixed64,2,opt,name=total_current_value,json=totalCurrentValue,proto3" json:"total_current_value,omitempty"`
	TotalUnrealizedPnl    float64                `protobuf:"fixed64,3,opt,name=total_unrealized_pnl,json=totalUnrealizedPnl,proto3" json:"total_unrealized_pnl,omitempty"`
	TotalUnrealizedPnlPct float64                `protobuf:"fixed64,4,opt,name=total_unrealized_pnl_pct,json=totalUnrealizedPnlPct,proto3" json:"total_unrealized_pnl_pct,omitempty"`
	TotalPositions        int32                  `protobuf:"varint,5,opt,name=total_positions,json=totalPositions,proto3" json:"total_positions,omitempty"`
	ActivePositions       int32                  `protobuf:"varint,6,opt,name=active_positions,json=activePositions,proto3" json:"active_positions,omitempty"`
	Categories            []*CategoryAggregation `protobuf:"bytes,7,rep,name=categories,proto3" json:"categories,omitempty"`
	Positions             []*Position            `protobuf:"bytes,8,rep,name=positions,proto3" json:"positions,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PositionAggregation) Reset() {
	*x = PositionAggregation{}
	mi := &file_position_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionAggregation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionAggregation) ProtoMessage() {}

func (x *PositionAggregation) ProtoReflect() protoreflect.Message {
	mi := &file_position_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionAggregation.ProtoReflect.Descriptor instead.
func (*PositionAggregation) Descriptor() ([]byte, []int) {
	return file_position_service_proto_rawDescGZIP(), []int{9}
}

func (x *PositionAggregation) GetTotalInvested() float64 {
	if x != nil {
		return x.TotalInvested
	}
	return 0
}

func (x *PositionAggregation) GetTotalCurrentValue() float64 {
	if x != nil {
		return x.TotalCurrentValue
	}
	return 0
}

func (x *PositionAggregation) GetTotalUnrealizedPnl() float64 {
	if x != nil {
		return x.TotalUnrealizedPnl
	}
	return 0
}

func (x *PositionAggregation) GetTotalUnrealizedPnlPct() float64 {
	if x != nil {
		return x.TotalUnrealizedPnlPct
	}
	return 0
}

func (x *PositionAggregation) GetTotalPositions() int32 {
	if x != nil {
		return x.TotalPositions
	}
	return 0
}

func (x *PositionAggregation) GetActivePositions() int32 {
	if x != nil {
		return x.ActivePositions
	}
	return 0
}

func (x *PositionAggregation) GetCategories() []*CategoryAggregation {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *PositionAggregation) GetPositions() []*Position {
	if x != nil {
		return x.Positions
	}
	return nil
}

// CategoryAggregation contains aggregated data by asset category
type CategoryAggregation struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CategoryId         int32                  `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	CategoryName       string                 `protobuf:"bytes,2,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	TotalInvested      float64                `protobuf:"fixed64,3,opt,name=total_invested,json=totalInvested,proto3" json:"total_invested,omitempty"`
	TotalCurrentValue  float64                `protobuf:"fixed64,4,opt,name=total_current_value,json=totalCurrentValue,proto3" json:"total_current_value,omitempty"`
	TotalUnrealizedPnl float64                `protobuf:"fixed64,5,opt,name=total_unrealized_pnl,json=totalUnrealizedPnl,proto3" json:"total_unrealized_pnl,omitempty"`
	UnrealizedPnlPct   float64                `protobuf:"fixed64,6,opt,name=unrealized_pnl_pct,json=unrealizedPnlPct,proto3" json:"unrealized_pnl_pct,omitempty"`
	PositionCount      int32                  `protobuf:"varint,7,opt,name=position_count,json=positionCount,proto3" json:"position_count,omitempty"`
	WeightPct          float64                `protobuf:"fixed64,8,opt,name=weight_pct,json=weightPct,proto3" json:"weight_pct,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CategoryAggregation) Reset() {
	*x = CategoryAggregation{}
	mi := &file_position_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryAggregation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryAggregation) ProtoMessage() {}

func (x *CategoryAggregation) ProtoReflect() protoreflect.Message {
	mi := &file_position_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryAggregation.ProtoReflect.Descriptor instead.
func (*CategoryAggregation) Descriptor() ([]byte, []int) {
	return file_position_service_proto_rawDescGZIP(), []int{10}
}

func (x *CategoryAggregation) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CategoryAggregation) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *CategoryAggregation) GetTotalInvested() float64 {
	if x != nil {
		return x.TotalInvested
	}
	return 0
}

func (x *CategoryAggregation) GetTotalCurrentValue() float64 {
	if x != nil {
		return x.TotalCurrentValue
	}
	return 0
}

func (x *CategoryAggregation) GetTotalUnrealizedPnl() float64 {
	if x != nil {
		return x.TotalUnrealizedPnl
	}
	return 0
}

func (x *CategoryAggregation) GetUnrealizedPnlPct() float64 {
	if x != nil {
		return x.UnrealizedPnlPct
	}
	return 0
}

func (x *CategoryAggregation) GetPositionCount() int32 {
	if x != nil {
		return x.PositionCount
	}
	return 0
}

func (x *CategoryAggregation) GetWeightPct() float64 {
	if x != nil {
		return x.WeightPct
	}
	return 0
}

var File_position_service_proto protoreflect.FileDescriptor

const file_position_service_proto_rawDesc = "" +
	"\n" +
	"\x16position_service.proto\x12\x0fhub_investments\x1a\fcommon.proto\"~\n" +
	"\x13GetPositionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\x06symbol\x18\x02 \x01(\tH\x00R\x06symbol\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x03 \x01(\tH\x01R\x06status\x88\x01\x01B\t\n" +
	"\a_symbolB\t\n" +
	"\a_status\"\x90\x01\n" +
	"\x14GetPositionsResponse\x12?\n" +
	"\fapi_response\x18\x01 \x01(\v2\x1c.hub_investments.APIResponseR\vapiResponse\x127\n" +
	"\tpositions\x18\x02 \x03(\v2\x19.hub_investments.PositionR\tpositions\"8\n" +
	"\x1dGetPositionAggregationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xa9\x01\n" +
	"\x1eGetPositionAggregationResponse\x12?\n" +
	"\fapi_response\x18\x01 \x01(\v2\x1c.hub_investments.APIResponseR\vapiResponse\x12F\n" +
	"\vaggregation\x18\x02 \x01(\v2$.hub_investments.PositionAggregationR\vaggregation\"\x99\x02\n" +
	"\x15CreatePositionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x01R\bquantity\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12#\n" +
	"\rposition_type\x18\x05 \x01(\tR\fpositionType\x12+\n" +
	"\x0fsource_order_id\x18\x06 \x01(\tH\x00R\rsourceOrderId\x88\x01\x01\x12&\n" +
	"\fcreated_from\x18\a \x01(\tH\x01R\vcreatedFrom\x88\x01\x01B\x12\n" +
	"\x10_source_order_idB\x0f\n" +
	"\r_created_from\"\xbd\x01\n" +
	"\x16CreatePositionResponse\x12?\n" +
	"\fapi_response\x18\x01 \x01(\v2\x1c.hub_investments.APIResponseR\vapiResponse\x12\x1f\n" +
	"\vposition_id\x18\x02 \x01(\tR\n" +
	"positionId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12)\n" +
	"\x10total_investment\x18\x04 \x01(\x01R\x0ftotalInvestment\"\xbb\x02\n" +
	"\x15UpdatePositionRequest\x12\x1f\n" +
	"\vposition_id\x18\x01 \x01(\tR\n" +
	"positionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12%\n" +
	"\x0etrade_quantity\x18\x03 \x01(\x01R\rtradeQuantity\x12\x1f\n" +
	"\vtrade_price\x18\x04 \x01(\x01R\n" +
	"tradePrice\x12 \n" +
	"\fis_buy_order\x18\x05 \x01(\bR\n" +
	"isBuyOrder\x12+\n" +
	"\x0fsource_order_id\x18\x06 \x01(\tH\x00R\rsourceOrderId\x88\x01\x01\x12*\n" +
	"\x0eexecution_time\x18\a \x01(\tH\x01R\rexecutionTime\x88\x01\x01B\x12\n" +
	"\x10_source_order_idB\x11\n" +
	"\x0f_execution_time\"\xe6\x03\n" +
	"\x16UpdatePositionResponse\x12?\n" +
	"\fapi_response\x18\x01 \x01(\v2\x1c.hub_investments.APIResponseR\vapiResponse\x12\x1f\n" +
	"\vposition_id\x18\x02 \x01(\tR\n" +
	"positionId\x12!\n" +
	"\fnew_quantity\x18\x03 \x01(\x01R\vnewQuantity\x12*\n" +
	"\x11new_average_price\x18\x04 \x01(\x01R\x0fnewAveragePrice\x120\n" +
	"\x14new_total_investment\x18\x05 \x01(\x01R\x12newTotalInvestment\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12)\n" +
	"\x10transaction_type\x18\a \x01(\tR\x0ftransactionType\x12&\n" +
	"\frealized_pnl\x18\b \x01(\x01H\x00R\vrealizedPnl\x88\x01\x01\x12-\n" +
	"\x10realized_pnl_pct\x18\t \x01(\x01H\x01R\x0erealizedPnlPct\x88\x01\x01\x12)\n" +
	"\x10events_published\x18\n" +
	" \x01(\x05R\x0feventsPublishedB\x0f\n" +
	"\r_realized_pnlB\x13\n" +
	"\x11_realized_pnl_pct\"\x9b\x04\n" +
	"\bPosition\x12\x1f\n" +
	"\vposition_id\x18\x01 \x01(\tR\n" +
	"positionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x01R\bquantity\x12#\n" +
	"\raverage_price\x18\x05 \x01(\x01R\faveragePrice\x12)\n" +
	"\x10total_investment\x18\x06 \x01(\x01R\x0ftotalInvestment\x12#\n" +
	"\rcurrent_price\x18\a \x01(\x01R\fcurrentPrice\x12!\n" +
	"\fmarket_value\x18\b \x01(\x01R\vmarketValue\x12%\n" +
	"\x0eunrealized_pnl\x18\t \x01(\x01R\runrealizedPnl\x12,\n" +
	"\x12unrealized_pnl_pct\x18\n" +
	" \x01(\x01R\x10unrealizedPnlPct\x12#\n" +
	"\rposition_type\x18\v \x01(\tR\fpositionType\x12\x16\n" +
	"\x06status\x18\f \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\tR\tupdatedAt\x12'\n" +
	"\rlast_trade_at\x18\x0f \x01(\tH\x00R\vlastTradeAt\x88\x01\x01B\x10\n" +
	"\x0e_last_trade_at\"\xaa\x03\n" +
	"\x13PositionAggregation\x12%\n" +
	"\x0etotal_invested\x18\x01 \x01(\x01R\rtotalInvested\x12.\n" +
	"\x13total_current_value\x18\x02 \x01(\x01R\x11totalCurrentValue\x120\n" +
	"\x14total_unrealized_pnl\x18\x03 \x01(\x01R\x12totalUnrealizedPnl\x127\n" +
	"\x18total_unrealized_pnl_pct\x18\x04 \x01(\x01R\x15totalUnrealizedPnlPct\x12'\n" +
	"\x0ftotal_positions\x18\x05 \x01(\x05R\x0etotalPositions\x12)\n" +
	"\x10active_positions\x18\x06 \x01(\x05R\x0factivePositions\x12D\n" +
	"\n" +
	"categories\x18\a \x03(\v2$.hub_investments.CategoryAggregationR\n" +
	"categories\x127\n" +
	"\tpositions\x18\b \x03(\v2\x19.hub_investments.PositionR\tpositions\"\xd8\x02\n" +
	"\x13CategoryAggregation\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\x05R\n" +
	"categoryId\x12#\n" +
	"\rcategory_name\x18\x02 \x01(\tR\fcategoryName\x12%\n" +
	"\x0etotal_invested\x18\x03 \x01(\x01R\rtotalInvested\x12.\n" +
	"\x13total_current_value\x18\x04 \x01(\x01R\x11totalCurrentValue\x120\n" +
	"\x14total_unrealized_pnl\x18\x05 \x01(\x01R\x12totalUnrealizedPnl\x12,\n" +
	"\x12unrealized_pnl_pct\x18\x06 \x01(\x01R\x10unrealizedPnlPct\x12%\n" +
	"\x0eposition_count\x18\a \x01(\x05R\rpositionCount\x12\x1d\n" +
	"\n" +
	"weight_pct\x18\b \x01(\x01R\tweightPct2\xaf\x03\n" +
	"\x0fPositionService\x12[\n" +
	"\fGetPositions\x12$.hub_investments.GetPositionsRequest\x1a%.hub_investments.GetPositionsResponse\x12y\n" +
	"\x16GetPositionAggregation\x12..hub_investments.GetPositionAggregationRequest\x1a/.hub_investments.GetPositionAggregationResponse\x12a\n" +
	"\x0eCreatePosition\x12&.hub_investments.CreatePositionRequest\x1a'.hub_investments.CreatePositionResponse\x12a\n" +
	"\x0eUpdatePosition\x12&.hub_investments.UpdatePositionRequest\x1a'.hub_investments.UpdatePositionResponseB\tZ\a./protob\x06proto3"

var (
	file_position_service_proto_rawDescOnce sync.Once
	file_position_service_proto_rawDescData []byte
)

func file_position_service_proto_rawDescGZIP() []byte {
	file_position_service_proto_rawDescOnce.Do(func() {
		file_position_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_position_service_proto_rawDesc), len(file_position_service_proto_rawDesc)))
	})
	return file_position_service_proto_rawDescData
}

var file_position_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_position_service_proto_goTypes = []any{
	(*GetPositionsRequest)(nil),            // 0: hub_investments.GetPositionsRequest
	(*GetPositionsResponse)(nil),           // 1: hub_investments.GetPositionsResponse
	(*GetPositionAggregationRequest)(nil),  // 2: hub_investments.GetPositionAggregationRequest
	(*GetPositionAggregationResponse)(nil), // 3: hub_investments.GetPositionAggregationResponse
	(*CreatePositionRequest)(nil),          // 4: hub_investments.CreatePositionRequest
	(*CreatePositionResponse)(nil),         // 5: hub_investments.CreatePositionResponse
	(*UpdatePositionRequest)(nil),          // 6: hub_investments.UpdatePositionRequest
	(*UpdatePositionResponse)(nil),         // 7: hub_investments.UpdatePositionResponse
	(*Position)(nil),                       // 8: hub_investments.Position
	(*PositionAggregation)(nil),            // 9: hub_investments.PositionAggregation
	(*CategoryAggregation)(nil),            // 10: hub_investments.CategoryAggregation
	(*APIResponse)(nil),                    // 11: hub_investments.APIResponse
}
var file_position_service_proto_depIdxs = []int32{
	11, // 0: hub_investments.GetPositionsResponse.api_response:type_name -> hub_investments.APIResponse
	8,  // 1: hub_investments.GetPositionsResponse.positions:type_name -> hub_investments.Position
	11, // 2: hub_investments.GetPositionAggregationResponse.api_response:type_name -> hub_investments.APIResponse
	9,  // 3: hub_investments.GetPositionAggregationResponse.aggregation:type_name -> hub_investments.PositionAggregation
	11, // 4: hub_investments.CreatePositionResponse.api_response:type_name -> hub_investments.APIResponse
	11, // 5: hub_investments.UpdatePositionResponse.api_response:type_name -> hub_investments.APIResponse
	10, // 6: hub_investments.PositionAggregation.categories:type_name -> hub_investments.CategoryAggregation
	8,  // 7: hub_investments.PositionAggregation.positions:type_name -> hub_investments.Position
	0,  // 8: hub_investments.PositionService.GetPositions:input_type -> hub_investments.GetPositionsRequest
	2,  // 9: hub_investments.PositionService.GetPositionAggregation:input_type -> hub_investments.GetPositionAggregationRequest
	4,  // 10: hub_investments.PositionService.CreatePosition:input_type -> hub_investments.CreatePositionRequest
	6,  // 11: hub_investments.PositionService.UpdatePosition:input_type -> hub_investments.UpdatePositionRequest
	1,  // 12: hub_investments.PositionService.GetPositions:output_type -> hub_investments.GetPositionsResponse
	3,  // 13: hub_investments.PositionService.GetPositionAggregation:output_type -> hub_investments.GetPositionAggregationResponse
	5,  // 14: hub_investments.PositionService.CreatePosition:output_type -> hub_investments.CreatePositionResponse
	7,  // 15: hub_investments.PositionService.UpdatePosition:output_type -> hub_investments.UpdatePositionResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_position_service_proto_init() }
func file_position_service_proto_init() {
	if File_position_service_proto != nil {
		return
	}
	file_common_proto_init()
	file_position_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_position_service_proto_msgTypes[4].OneofWrappers = []any{}
	file_position_service_proto_msgTypes[6].OneofWrappers = []any{}
	file_position_service_proto_msgTypes[7].OneofWrappers = []any{}
	file_position_service_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_position_service_proto_rawDesc), len(file_position_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_position_service_proto_goTypes,
		DependencyIndexes: file_position_service_proto_depIdxs,
		MessageInfos:      file_position_service_proto_msgTypes,
	}.Build()
	File_position_service_proto = out.File
	file_position_service_proto_goTypes = nil
	file_position_service_proto_depIdxs = nil
}
